name: Cloudflare Pages Deploy
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_PAGES_NAME: ${{ secrets.CLOUDFLARE_PAGES_NAME }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          curl "https://api.cloudflare.com/client/v4/accounts/${{ CLOUDFLARE_ACCOUNT_ID }}/pages/projects/${{ CLOUDFLARE_PAGES_NAME }}/deployments" \
          -H "Content-Type: multipart/form-data" \
          -H "Authorization: Bearer ${{ CLOUDFLARE_API_TOKEN }}" \
          -F branch=main
